version: '2.4'
services:
  nginx-proxy:
    image: my-nginx
    volumes_from:
      - container:${container_id}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy-net
networks:
  proxy-net: 
    driver: bridge
